web/reNgine/tasks.py
fix #17 
Problem comes when a file fuzzing was launched on the target (scan) and not on the subdomain (subscan).
subdomain_var does not exists while launching a scan from a target so a simple existence check resolve the problem and the subdomain is extracted from the endpoint
tested and working
=> fix(file_fuzz): subdomain_id key error

default_yaml_config.yaml, web/reNgine/common_func.py, web/reNgine/tasks.py, web/scanEngine/templates/scanEngine/_items/form_engine.html
fix #19 
I've refactored all the code that generate headers
Given the case that each tool has his proper format, although it is the same between multiple tools, I've decide to write some functions to manage every case properly.
Also, now 2 formats are compatible :
- old one, string, like `custom_header: 'Cookie: Test'`, for backward compatibility
- new one, a dictionary, more flexible, will replace the string format
```
custom_header: {
'Cookie':'Test',
'User-Agent': 'Mozilla/5.0',
'Custom-Header': 'My custom header'
}
```
Waiting feedback and test
=> refactor(scan): custom headers

web/reNgine/settings.py, web/reNgine/tasks.py, web/targetApp/views.py
fix #16 
Replace the `scan_id` sequential number by an `uuid`, hard to guess.
This quickly address the issue while we could think about a better solution when we will work on the #71 
I've also "normalize" the path :
```mermaid
graph LR;
A(/usr/src/scan_results)
B(/domain_name)
C(/subscans)
D(/scans)
E(/uuid)
A-->B;
B-->C;
B-->D;
C-->E;
D-->E;
```
=> fix(security): rework scan working folder location to prevent leaks

web/reNgine/tasks.py
I've made a mistake in #92 
I've retrieved the base path from the scan db table instead of the config
This gave the full path :  `base_path/domain/scans/uuid/subscans/uuid` instead of `base_path/domain/subscans/uuid` 
Only if you launch a subscan not a scan.
Fixed here, tested and working
=> fix(scan): fix bad base path retrieval for results dir

README.md, default_yaml_config.yaml, web/dashboard/views.py, web/reNgine/tasks.py, web/startScan/models.py, web/startScan/static/startScan/js/detail_scan.js, web/startScan/views.py, web/targetApp/views.py
Fix #7 #14 
With this PR **reNgine-ng** scans will work really better.
Check the issues for more details about the bug.
Now an endpoint is considered as alive **if an HTTP status code exists and is > 0**.
This prevent a lot of problems while running scan because in the current state if an endpoint returns **40x** or **50x** code, **it will not be scanned**.
This modification also correctly set the `is_default` state of the root endpoint of the subdomain that is the base of all the active scan (ffuf, nuclei ...)
There's also a problem with 301 and 302 status code.
In **reNgine-ng**, **HTTPx** was set to follow redirect by default, this creates bugs of scan not launched because the URL of the redirection is not the same as the scanned URL.
So I've switched the default value to **False**. To …
=> fix(scan): rework the alive endpoint and redirection operation

web/reNgine/tasks.py
Fix #18 
`save_subdomain` function can return **None** in some case, so I've added the condition to verify if an object of type **Subdomain** is returned.
If not, skip record, log error and continue loop
It fixes issue, bug I've added this check on all `save_subdomain` call to prevent errors
=> fix(scan): check value returned for all subs saved

web/reNgine/tasks.py
Fix #101
I've reworked this part to update subdomain HTTP metadatas when an `http_crawl` scan is launched with no url
=> fix(scan): rework http_crawl to update subdomain datas

web/startScan/static/startScan/js/detail_scan.js
Fix #38 
HTML IDs resetted before displaying results
=> fix(ui): reset osint dork result id before display

web/celery-entrypoint.sh
Fix #15 
Read issue for details
As **EyeWitness** has been [patched](https://github.com/Security-Tools-Alliance/rengine-ng/issues/15#issuecomment-2146609574), the bug above should be fixed when you restart the celery container, but not ...
So I've added a condition, when directory exists, for every tool, to update it by git pulling
So now **EyeWitness** bug need a simple `make stop`, `make restart` to be fixed
I've also:
- silent the **pip** output that makes the status of the tools update not visible
- fixed a small path bug for **gf**, this could improve things because this fix prevent the **tomnomnom** gf pattern copy to fail
=> fix(tools): update git tools at startup

web/reNgine/common_func.py, web/reNgine/tasks.py
fix #112 
I've added a function to check if a variable is an iterable
=> fix(scan): add some iterable checks to prevent TypeError

web/reNgine/tasks.py, web/static/custom/custom.js
Fix #117 
Request/response values are escaped before adding to the db and displayed in a <pre> in the UI
Testes and working using the payload given in the issue
=> fix(ui): escape vulnerability request/response in db and display in ui

README.md
=> fix(readme): remove space after url

docker/celery/Dockerfile
#139 reintroduces hardcoded amd64 arch packages
Fixed by copying go and gecko install from the currently working Dockerfile on master
Not tested, I don't have any arm64 arch
@0b3ud @AnonymousWP 
Could you do the test below ?
=> build(docker): add ARM support for Celery Dockerfile

web/static/assets/js/app.min.js, web/static/custom/custom.js, web/templates/base/base.html
fixes #11 
Permit to link tab URL and history back into it
Tabs use tags like this
`scan/default/detail/1#endpoints-tab`
So you could copy/paste the link and share it
You can also navigate to previous tab with history back button
=> fix(ui): permit to link tab URL and history back into it

web/startScan/static/startScan/js/detail_scan.js, web/static/custom/custom.js
=> fix(ui): stored XSS

install.sh
We need to revert the value, it creates problem when installing
This should be merged ASAP
=> fix(install): revert changes of prebuilt chain

.github/workflows/build.yml, .vscode/tasks.json
Fix #106
First PoC to automate docker images creation
This need tests
Here are the main modifications and their explanations:
1. I added triggers for pull requests, pushes to `master` and `release/**`, tags `v*.*.*`, and published releases.
2. I defined environment variables for the registry, owner, and project name to facilitate maintenance.
3. I used a matrix to build all images defined in `tasks.json`.
4. I modified the `docker/metadata-action` configuration to generate appropriate tags, including the `latest` tag for the default branch.
5. I adjusted the context and Dockerfile path in `docker/build-push-action` to match your project structure.
6. I added an `update-release` job that runs only when a release is published. This job updates the release description with the list of Docker …
=> build(ci): build docker images for each tag, release, push

.github/workflows/build.yml, .github/workflows/delete-untagged-images.yml
Image creation has been restricted to the docker folder
Tags are now generated for the current services, and version (eg: rengine-celery-v2.1.0)
I've also added a manual workflow to remove untagged images
=> build(images): restrict image creation, add correct tags and clean non tagged images

web/reNgine/common_func.py, web/reNgine/settings.py, web/reNgine/tasks.py, web/startScan/templates/startScan/schedule_scan_list.html, web/startScan/templates/startScan/schedule_scan_ui.html, web/startScan/views.py
Fixes #181 
Periodic and schedule scan are now working again.
There was also an UTC time problem.
So the timezone offset is gathered from the user browser and start datetime of the scan are send to beat in UTC if there's an interval
=> fix(scan): fix clocked and scheduled scan not working

web/api/serializers.py, web/api/views.py, web/static/custom/mitch.js
Fixes #124 
With this PR dorks and vulnerabilites are deduplicated to improve graph display on a lot of targets
Here with vulnweb.com targets
=> fix(graph): de-duplicate dorks and vulnerabilities

.github/workflows/codeql-analysis.yml
This PR gets rid of the cron-based scanning, and now always scans for code improvements upon every PR or push. It also uses [the extra suite](https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning#using-queries-in-ql-packs) `security-and-quality`. Finally, to prevent the workflow from running, text and Markdown files are ignored.
=> build(ci): improve CodeQL configuration

web/scanEngine/templates/scanEngine/settings/tool_arsenal.html
- Disabled the "Check Update" button in the Tool Arsenal section and replaced it with a placeholder indicating that the update feature is coming soon.
As we have moved to a poetry management for the python libs, permit update could break things.
When issue #143 will be solved we could restablish the update system.
Anyway we will frequently push new images with latest tool
=> feat(ui): disable update button in tool arsenal

Makefile, install.sh
Fix #247
- Define and uses a new environment variable, RENGINE_FOLDER, to specify the reNgine installation directory. 
- Fix non interactive argument check not working while using sudo command
=> fix(install): set rengine folder correctly & fix non interactive argument check

web/commonFilters/templatetags/custom_filters.py, web/dashboard/templates/dashboard/admin.html, web/dashboard/tests/test_dashboard.py, web/dashboard/utils.py, web/dashboard/views.py
Fix #241 
This change introduces several fixes to the `sys_admin` role. 
- Better check the project list to prevent new sys admins to be stucked on **Welcome** page
- Refines the permissions of the user administration actions to prevent `superuser` profile edition by `sys_admin`, only superuser can edit superuser
- Clarify user roles in the administrator interface.
=> fix: rework sys_admin authorizations

docker/docker-compose.yml, install.sh, web/templates/base/_items/top_bar.html, web/templates/base/base.html
fix #263 
Improve installation script and update handling from version below 2.1.0
This set of changes enhances the installation script and update mechanism of reNgine-ng. The installation script now handles potential issues with Docker images and volumes, ensuring a smoother installation process. The update check has been improved to reduce API calls and provide a better user experience. Additionally, configuration files for certain tools are now managed during installation.
=> fix: resolve bug during upgrade from 2.0.7

.github/workflows/close-issues-on-pr-merge-to-release-branch.yml
This pull request significantly improves the workflow for automatically closing issues linked to pull requests merged into a release branch. Instead of only closing a single issue referenced in the PR body, the workflow now accurately identifies and closes all issues that GitHub would automatically link and close, matching the UI behavior. It uses the GitHub GraphQL API for robust detection and includes better error handling and feedback.
**Automation improvements:**
* Replaces the previous approach of extracting a single issue number from the PR body with a script that uses GitHub's GraphQL API to fetch all issues linked to the pull request (i.e., those shown in the UI as "will be closed by this PR"), ensuring all relevant issues are targeted.
* Adds robust error handling for API …
=> build(ci): close all linked issues on PR merge to release branch
